#:kivy 2.0.0

<Gerenciador>:
    Tarefas:


<Tarefas>:
    name: 'Tarefas'
    BoxLayout:
        orientation:'vertical'
        ScrollView:
            BoxLayout:
                id: box
                orientation: 'vertical'
                size_hint_y:None
                height:self.minimum_height
        BoxLayout:
            size_hint_y:None
            height:60

            TextInput:
                id:texto

            Button:
                size_hint_x:None
                widht:60
                text:'+!'
                on_release:root.addWidget()

<Tarefa>:
    size_hint_y:None
    height:200

    Label:
        id:label
        font_size:30

    Button:
        size_hint_x:None
        widht:60
        text:'X'
        on_release:app.root.get_screen('Tarefas').ids.box.remove_widget(self.parent)